// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/fetch-css': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fetch-css').default>>>>
    }
    '/api/kubus': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kubus').default>>>>
    }
    '/api/kulso-tokos-aluminium-redon': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kulso-tokos-aluminium-redon').default>>>>
    }
    '/api/linear': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/linear').default>>>>
    }
    '/api/m-9000-bejarati-ajtok': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-9000-bejarati-ajtok').default>>>>
    }
    '/api/m-9000-emelo-tolo-ajto': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-9000-emelo-tolo-ajto').default>>>>
    }
    '/api/m-9000-tolo-buko-ajtok': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-9000-tolo-buko-ajtok').default>>>>
    }
    '/api/m-9000': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-9000').default>>>>
    }
    '/api/m-eco-bejarati-ajto': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-eco-bejarati-ajto').default>>>>
    }
    '/api/m-eco': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-eco').default>>>>
    }
    '/api/m-oc-bejarati-ajto': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-oc-bejarati-ajto').default>>>>
    }
    '/api/m-oc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/m-oc').default>>>>
    }
    '/api/raepitheto-tokos-aluminium-redony': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/raepitheto-tokos-aluminium-redony').default>>>>
    }
    '/api/raepitheto-tokos-muanyag-redony': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/raepitheto-tokos-muanyag-redony').default>>>>
    }
    '/api/redex-kulso-tokos-muanyag-redony': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redex-kulso-tokos-muanyag-redony').default>>>>
    }
    '/api/sitemap': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap').default>>>>
    }
    '/api/smoovio-toloajto': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/smoovio-toloajto').default>>>>
    }
    '/api/vakolhato-tokos-aluminium-redony': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vakolhato-tokos-aluminium-redony').default>>>>
    }
    '/api/vakolhato-tokos-muanyag-redony': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vakolhato-tokos-muanyag-redony').default>>>>
    }
    '/api/window_sitemap': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/window_sitemap').default>>>>
    }
    '/api/window_variations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/window_variations').default>>>>
    }
    '/api/zip-screen': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/zip-screen').default>>>>
    }
    '/api/zsaluzia-2': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/zsaluzia-2').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-site-config/dist/runtime/nitro/routes/__site-config__/debug').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap_index.xml').default>>>>
    }
    '/pages-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/postwindow-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/blog-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xml').default>>>>
    }
    '/mail/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-mail/dist/server-handler.post').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}